// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qizfozttjbzcjnsilklo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFpemZvenR0amJ6Y2puc2lsa2xvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNTkwNDYsImV4cCI6MjA2MjczNTA0Nn0.EBhKlxw-1iQZu5t1WkEFX1asdEshTBImfvHuARZKkWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);